MGComics/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("SecondSight.urls"))
]

SecondSight/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('Sticky/New/', views.sticky_new, name='sticky_new'),
    path('Sticky/<int:pk>/edit/', views.sticky_edit, name='sticky_edit'),
    path('Sticky/<int:pk>/manage/', views.sticky_manage, name='sticky_manage'),
    path('Sticky/<int:pk>/delete/', views.sticky_delete, name='sticky_delete'),
    path('News/', views.news_list, name='news'),
    path('News/<int:pk>/', views.news_detail, name='news_detail'),
    path('News/Post/', views.news_post, name='news_post'),
    path('News/<int:pk>/edit/', views.news_edit, name='news_edit'),
    path('News/<int:pk>/manage/', views.news_manage, name='news_manage'),
    path('News/<int:pk>/delete/', views.news_delete, name='news_delete'),
    path('About/', views.about, name='about'),
    path('Archive/', views.comic_list, name='archive'),
    path('Comic/<int:pk>/', views.comic_detail, name='comic_detail'),
    path('Comic/New/', views.comic_new, name='comic_new'),
    path('Comic/<int:pk>/edit', views.comic_edit, name='comic_edit'),
    path('Extras/', views.extras_list, name='extras'),
    path('Gallery/', views.gallery, name='gallery'),
    path('Gallery/New/', views.gallery_new, name='gallery_new'),
    path('Gallery/<int:pk>/', views.gallery_detail, name='gallery_detail'),
    path('Gallery/<int:pk>/edit/', views.gallery_edit, name='gallery_edit'),
    path('Gallery/<int:pk>/manage/', views.gallery_manage, name='gallery_manage'),
    path('Gallery/<int:pk>/delete/', views.gallery_delete, name='gallery_delete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SecondSight/models.py
from django.db import models
from django.utils import timezone


STATUS = (
    ('s', "Show"),
    ('', "Hide"),
    ('d', 'DELETE')
)


# News blog model 
class Newspost(models.Model):
    image = models.ImageField(upload_to='images/', blank=True, default='')
    title = models.CharField(max_length=50)
    group_id = models.CharField(max_length=50)
    text = models.TextField(max_length=5000)
    created_date = models.DateTimeField(default=timezone.now)
    manage = models.CharField(max_length=10, choices=STATUS, blank=True, default='')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.title


# About model
class User(models.Model):
    name = models.CharField(max_length=25, blank=True, default='')
    image = models.ImageField(upload_to='images/', blank=True, default='')
    description = models.TextField(max_length=900, blank=True, default='')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name


# Sticky model
class Sticky(models.Model):
    name = models.CharField(max_length=25, blank=True, default='')
    image = models.ImageField(upload_to='images/', blank=True, default='')
    description = models.TextField(max_length=900, blank=True, default='')
    status = models.CharField(max_length=50, blank=True, default='')
    date = models.CharField(max_length=50, blank=True, default='')
    manage = models.CharField(max_length=10, choices=STATUS, blank=True, default='')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name


class Chapter(models.Model):
    title = models.CharField(max_length=50, blank=True, default='')
    image = models.ImageField(upload_to='images/')
    description = models.TextField()

    def __str__(self):
        return self.title


# Comic model
class Comic(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    page_number = models.IntegerField()
    group_id = models.CharField(max_length=50, blank=True, default='')
    description = models.CharField(max_length=500, blank=True, default='')
    transcript = models.CharField(max_length=500, blank=True, default='')

    def __str__(self):
        return self.title

# Gallery Model
class Image(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    description = models.CharField(max_length=500, blank=True, default='')
    manage = models.CharField(max_length=10, choices=STATUS, blank=True, default='')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.title

# cover banner
class CoverBanner(models.Model):
    title = models.CharField(max_length=50, blank=True, default='')
    image = models.ImageField(upload_to='images/')
    tag_line = models.CharField(max_length=900, blank=True, default='')
    description = models.CharField(max_length=900, blank=True, default='')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.title

SecondSight/forms.py
from django import forms
from django.utils import timezone


from .models import *

class NewsForm(forms.ModelForm):
    class Meta:
        model = Newspost
        fields = [
            'title',
            'image',
            'group_id',
            'text',
            'manage',
        ]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'name',
            'image',
            'description',
        ]


class StickyForm(forms.ModelForm):
    class Meta:
        model = Sticky
        fields = [
            'name',
            'image',
            'description',
            'status',
            'date',
            'manage',
        ]


class ComicForm(forms.ModelForm):
    class Meta:
        model = Comic
        fields = [
            'title',
            'image',
            'chapter',
            'page_number',
            'group_id',
            'description',
            'transcript',
        ]


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = [
            'title',
            'image',
            'description',
            'manage',
        ]

SecondSight/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.forms.models import model_to_dict
from django.utils import timezone

from . import models
from . import forms


#GLOBALS


# index View
def index(request):
    post = []
    all_posts = models.Newspost.objects.filter(Q(manage__contains='s') 
        | Q(manage__contains='d')).order_by('-id')
    for i in all_posts:
        post.append(i)

    comics = []
    all_comics = models.Comic.objects.all().order_by('id')
    for comic in all_comics:
        comics.append(comic)

    sticky = []
    all_posts2 = models.Sticky.objects.all().order_by('id')
    for i in all_posts2:
        sticky.append(i)

    first = []
    first_comic = models.Comic.objects.all().order_by('page_number')
    for i in first_comic:
        first.append(i)

    last = []
    last_comic = models.Comic.objects.all().order_by('-page_number')
    for i in last_comic:
        last.append(i)

    cover_banner = []
    banners= models.CoverBanner.objects.all().order_by('-id')
    for i in banners:
        cover_banner.append(i)

    return render(request, 'secondsight/index.html', {
                    'post': post[0],
                    'comics': comics,
                    'sticky': sticky,
                    "first": first[0],
                    "last": last[0],
                    "cover_banner": cover_banner[0]
                    })

# New Sticky
def sticky_new(request):
    title = 'Submit a New Sticky.'
    if request.method == "POST":
        form = forms.StickyForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.created_date = timezone.now()
            form.save()
            return redirect('index')
    else:
        form = forms.StickyForm()
    return render(request, 'secondsight/new.html', {
                    'form': form,
                    'title': title
                    })

def sticky_edit(request, pk):
    title = 'Edit Post'
    post = get_object_or_404(models.Sticky, pk=pk)
    form = forms.StickyForm(instance=post)
    if request.method == "POST":
        form = forms.StickyForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('sticky_manage', pk)
    return render(request, 'secondsight/new.html', {
                    'form': form,
                    'title': title
                    })

def sticky_manage(request, pk):
    sticky = model_to_dict(get_object_or_404(models.Sticky, pk=pk))
    return render(request, 'secondsight/sticky_manage.html',{
                    "sticky": sticky,
                    })

def sticky_delete(request, pk):
    sticky = get_object_or_404(models.Sticky, pk=pk)
    sticky.delete()
    return redirect('index')


# News View
def news_list(request):
    """List the 10 most recent News Posts"""
    posts = []
    all_posts = models.Newspost.objects.all().order_by('-id')[:10]
    for post in all_posts:
        posts.append(post)

    comics = []
    all_comics = models.Comic.objects.all().order_by('id')
    for comic in all_comics:
        comics.append(comic)

    first = []
    first_comic = models.Comic.objects.all().order_by('page_number')
    for i in first_comic:
        first.append(i)

    last = []
    last_comic = models.Comic.objects.all().order_by('-page_number')
    for i in last_comic:
        last.append(i)

    sticky = []
    all_posts2 = models.Sticky.objects.all().order_by('id')
    for i in all_posts2:
        sticky.append(i)
    return render(request, 'secondsight/news_list.html', {
                    'posts': posts,
                    'comics': comics,
                    "first": first[0],
                    "last": last[0],
                    'sticky': sticky
                    })

# news detail view
def news_detail(request, pk):
    post = model_to_dict(get_object_or_404(models.Newspost, pk=pk))
    comics = models.Comic.objects.all(
            ).filter(Q(group_id__exact=post['group_id']))

    first = []
    first_comic = models.Comic.objects.all().order_by('page_number')
    for i in first_comic:
        first.append(i)

    last = []
    last_comic = models.Comic.objects.all().order_by('-page_number')
    for i in last_comic:
        last.append(i)

    return render(request, 'secondsight/news_detail.html',{
                    "post": post,
                    "comics": comics,
                    "first": first[0],
                    "last": last[0]
                    })

# news new/edit/delete
def news_post(request):
    title = 'Submit an Update.'
    if request.method == "POST":
        form = forms.NewsForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.created_date = timezone.now()
            form.save()
            return redirect('news')
    else:
        form = forms.NewsForm()
    return render(request, 'secondsight/new.html', {
                    'form': form,
                    'title': title
                    })

def news_edit(request, pk):
    title = 'Edit Post'
    post = get_object_or_404(models.Newspost, pk=pk)
    form = forms.NewsForm(instance=post)
    if request.method == "POST":
        form = forms.NewsForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('news_manage', pk)
    return render(request, 'secondsight/new.html', {
                    'form': form,
                    'title': title
                    })

def news_manage(request, pk):
    post = model_to_dict(get_object_or_404(models.Newspost, pk=pk))
    return render(request, 'secondsight/news_manage.html',{
                    "post": post,
                    })

def news_delete(request, pk):
    post = get_object_or_404(models.Newspost, pk=pk)
    post.delete()
    return redirect('news')

# About View
def about(request):
    users = []
    all_users = models.User.objects.all().order_by('id')
    for user in all_users:
        users.append(user)

    sticky = []
    all_posts2 = models.Sticky.objects.all().order_by('id')
    for i in all_posts2:
        sticky.append(i)

    first = []
    first_comic = models.Comic.objects.all().order_by('page_number')
    for i in first_comic:
        first.append(i)

    last = []
    last_comic = models.Comic.objects.all().order_by('-page_number')
    for i in last_comic:
        last.append(i)

    return render(request, 'secondsight/about.html', {
                    'users': users,
                    "first": first[0],
                    "last": last[0],
                    'sticky': sticky
                    })

# Archive View
def comic_list(request):
    chapters = models.Chapter.objects.all().order_by('id')

    first = []
    first_comic = models.Comic.objects.all().order_by('page_number')
    for i in first_comic:
        first.append(i)

    last = []
    last_comic = models.Comic.objects.all().order_by('-page_number')
    for i in last_comic:
        last.append(i)

    return render(request, 'secondsight/comic_list.html', {
                    'chapters': chapters,
                    "first": first[0],
                    "last": last[0]
                    })

def comic_detail(request, pk):
    comic = models.Comic.objects.get(id=pk)

    previous = models.Comic.objects.filter(Q(page_number__lt=comic.page_number) | Q(page_number=comic.page_number, id__lt=comic.id))
    if previous:
        previous = previous.order_by("-page_number", "id")[0]

    next = models.Comic.objects.filter(Q(page_number__gt=comic.page_number) | Q(page_number=comic.page_number, id__gt=comic.id))
    if next:
        next = next.order_by("page_number", "id")[0]

    first = []
    first_comic = models.Comic.objects.all().order_by('page_number')
    for i in first_comic:
        first.append(i)

    last = []
    last_comic = models.Comic.objects.all().order_by('-page_number')
    for i in last_comic:
        last.append(i)

    return render(request, 'secondsight/comic_detail.html',{
                    "comic": comic,
                    "first": first[0],
                    "last": last[0],
                    "previous": previous,
                    "next": next
                    })

# comic new/edit/delete
def comic_new(request):
    title = 'Submit a New Comic Page.'
    if request.method == "POST":
        form = forms.ComicForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.created_date = timezone.now()
            form.save()
            return redirect('archive')
    else:
        form = forms.ComicForm()
    return render(request, 'secondsight/new.html', {
                    'form': form,
                    'title': title
                    })

def comic_edit(request, pk):
    title = 'Edit Comic'
    post = get_object_or_404(models.Comic, pk=pk)
    form = forms.ComicForm(instance=post)
    if request.method == "POST":
        form = forms.ComicForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('archive')
    return render(request, 'secondsight/new.html', {
                    'form': form,
                    'title': title
                    })

# Extras View
def extras_list(request):
    images = []

    all_images = models.Image.objects.all().order_by('-id')[:7]
    for image in all_images:
        images.append(image)

    first = []
    first_comic = models.Comic.objects.all().order_by('page_number')
    for i in first_comic:
        first.append(i)

    last = []
    last_comic = models.Comic.objects.all().order_by('-page_number')
    for i in last_comic:
        last.append(i)

    return render(request, 'secondsight/extras_list.html', {

SecondSight/templates/secondsight/about.html
{% extends 'secondsight/layout.html' %}
{% load static %}

{% block content %}
<div class="header"></div>
<!--main content-->
{% for i in users %}
    <div class="main-content-about">
        {% if i.image %}
            <img src="/media/{{ i.image }}"></img>
        {% endif %}
        <h2>{{ i.name }}</h2>
        <p>{{ i.description|safe }}</p>
    </div>
{% endfor %}
<!--/main content-->
<!--right-sidebar-->
{% endblock %}

SecondSight/templates/secondsight/comic_detail.html
{% extends 'secondsight/layout.html' %}

{% block content %}
<div class="header"></div>
<!--main content-->
<div class="main-content-comic">
    <h1>
        {{ comic.title }}
        {% if user.is_authenticated %}
                <a href="{% url 'comic_edit' pk=comic.id %}"> | Edit</a>
        {% endif %}
    </h1>
    <img src="/media/{{ comic.image }}"></img>
    <h2>
        <a href="{% url 'comic_detail' pk=first.id %}"> <<< First </a>  | 
        {% if previous.id %}
            <a href="{% url 'comic_detail' pk=previous.id %}"> < Previous </a>  |  
        {% else %}
            < Previous   |  
        {% endif %}
        {% if next.id %}
            <a href="{% url 'comic_detail' pk=next.id %}"> Next > </a>  | 
        {% else %}
            Next >   |  
        {% endif %}
        <a href="{% url 'comic_detail' pk=last.id %}"> Last >>> </a>
    </h2>
</div>
{% if comic.description or comic.transcript %}
<div class="main-content-comic-description">
    <p>{{ comic.description }}</p>
    <h2>Transcipt</h2>
    <p>{{ comic.transcript }}</p>
</div>
{% endif %}
<!--/main content-->
{% endblock %}

SecondSight/templates/secondsight/comic_list.html
{% extends 'secondsight/layout.html' %}
{% load custom_tags %}

{% block content %}
<div class="header"></div>
<!--main content-->
{% for chapter in chapters %}
    <div class="main-content-comic">
        <img src="/media/{{ chapter.image }}"></img>
        <h1>{{ chapter.title }}</h1>
        <h2>{{ chapter.description }}</h2>
        <ul>
            {% for comic in chapter.comic_set.all|sort_by:'page_number' %}
                <li>
                    <a href="{% url 'comic_detail' pk=comic.id %}">
                        <img src="/media/{{ comic.image }}"></img>
                    </a>
                    <a href="{% url 'comic_detail' pk=comic.id %}">
                        <p>{{ comic.title|cut:"Page " }}</p>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endfor %}
<!--/main content-->
{% endblock %}

SecondSight/templates/secondsight/extras_gallery.html
{% extends 'secondsight/layout.html' %}

{% block content %}
<div class="header"></div>
<!--main content-->
<div class="main-content">
    <h2>Artwork</h2>
    <ul>
    {% for i in images %}
        <li>
            <a href="/media/{{ i.image }}">
                <img src="/media/{{ i.image }}"></img>
            </a>
            {% if user.is_authenticated %}
                <p><a href="{% url 'gallery_edit' pk=i.id %}">Edit</a></p>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
<!--/main content-->
</div>
{% endblock %}

SecondSight/templates/secondsight/extras_list.html
{% extends 'secondsight/layout.html' %}

{% block content %}
<div class="header"></div>
<!--main content-->
<div class="main-content">
    <h1><a href="{% url 'gallery' %}">Artwork</a></h1>
    <ul>
    {% for i in images %}
        <li>
            <a href="/media/{{ i.image }}">
                <img src="/media/{{ i.image }}"></img>
            </a>
        </li>
    {% endfor %}
    <li id="container">
        <a href="{% url 'gallery' %}">
            <img src="/static/secondsight/Button-TextureBBB.jpg"></img>
            <h1 id="centered">+++</h1>
        </a>
    </li>
</div>
<div class="main-content">
    <h1>Fanwork</h1>
    <p>Want to send me your Second Sight creations? You can email them to me at  mg@secondsightwebcomic.com or tag/dm me on Twitter, Tumblr and Facebook! I’m excited to see what you’ve made!
    </p>
    </div>
<div class="main-content">
    <h1>Cameos</h1>
    <p>
        Mars, Jia & Ren - Project Nought
In Chapter Two on Page Three, we have Mars, Jia, and the back of Ren's head. Project Nought, by Chelsey Furedi, is a fantastic webcomic that I cannot recommend highly enough. I was introduced to Furedi's work with their first title, Rock N' Riot, which I absolutely adored, and immediately jumped on board when they announced their new Project Nought in 2017.


Hotaru - Hotarugari
Also on Page Three of Chapter Two, there's a modernized and (completely) humanized version of Hotaru, the titular kitsune character from the webcomic Hotarugari by Salis. Hotaru normally has really cute fox ears and tail and a more...Japanese fantasy-esque look to his clothing, but I felt the need to draw him more "normal" for the sake of poor Keira's sanity on her stressful first day at school.

Alice, Corey, Jaden & Victoria - N.M.E.
Alice, Corey, Jaden, and Victoria appear a few times in Chapter Two on Pages Seven and Eight and Thirteen. These characters are also by Salis, and can be seen illustrated in their quirky, full-colored glory on Sal’ Tumblr page!
    </p>
</div>
<!--/main content-->
{% endblock %}

SecondSight/templates/secondsight/index.html
{% extends 'secondsight/layout.html' %}
{% load static %}

{% block content %}
{% if cover_banner %}
<div class="header" id="cover-banner">
    <img src="/media/{{ cover_banner.image}}"></img>
    <h2>{{ cover_banner.tag_line|safe }}</h2>
    <ul>
        <li>
            <a href="{% url 'comic_detail' pk=first.id %}" id="button-comic-nav">From the Beginning </a>
            <a href="{% url 'archive' %}" id="button-comic-nav">View Archive</a>
            <a href="{% url 'comic_detail' pk=last.id %}" id="button-comic-nav">Lastest Page</a>
        </li>
    </ul>
</div>
<div class="main-content">
    {{ cover_banner.description|safe }}
</div>
{% endif %}
<!--main content-->
{% if sticky %}
    {% for i in sticky %}
        {% if i.manage %}
            <div class="main-content-sticky">
                {% if i.image %}
                    <img src="/media/{{ i.image }}" id="banner"></img>
                {% endif %}
                <h2>STATUS: {{ i.status }}
                    {% if user.is_authenticated %}
                        <a href="{% url 'sticky_edit' pk=i.id %}"> | Edit</a>
                    {% endif %}
                </h2>
                <p>Next Update: {{ i.date }}</p>
                <p>{{ i.description|safe }}</p>
            </div>
        {% else %}
            {% if user.is_authenticated %}
                <div class="main-content-sticky">
                    {% if i.image %}
                        <img src="/media/{{ i.image }}" id="banner"></img>
                    {% endif %}
                    <h1>(HIDDEN)</h1>
                    <h2>STATUS: {{ i.status }} 
                        <a href="{% url 'sticky_edit' pk=i.id %}"> | Edit</a>
                    </h2>
                    <p>{{ i.date }}</p>
                    <p>{{ i.description|safe }}</p>
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
{% endif %}
<div class="main-content" >
    {% if post.image %}
        <img src="/media/{{ post.image }}" id="banner"></img>
    {% endif %}
    <h2>{{ post.title }}</h2>
    <p>{{ post.text|safe }}</p>
    <ul>
        {% for comic in comics %}
                {% if comic.group_id == post.group_id %}
                    <li>
                        <a href="{% url 'comic_detail' pk=comic.id %}">
                            <img src="/media/{{ comic.image }}"></img>
                        </a>
                    </li>
                {% endif %}
        {% endfor %}
    </ul>
</div>
<!--/main content-->
<!--right-sidebar-->
<!--/right-sidebar-->
{% endblock %}

SecondSight/templates/secondsight/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Second Sight</title>
    <meta name="description" content="A Web comic created by Michelle Grenz.">
    <meta name="author" content="Jonathan Grenz">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'secondsight/css/global.css' %}">
</head>
<body>
    <div class="main-nav">
        <ul class="nav">
            <a href="{% url 'index' %}">
                <img src="/static/secondsight/2022-SS-HeaderLogo4.png"></img>
            </a>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'news' %}">News</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'archive' %}">Archive</a></li>
            <!-- <li><a href="" target="_blank">Shop</a></li> -->
            <!-- <li><a href="{% url 'extras' %}">Extras</a></li> -->
        </ul>
    </div>
    <div class="admin-nav">
        {% if user.is_authenticated %}
            <a href="{% url 'news_post' %}" >New Update</a> | 
            <a href="{% url 'comic_new' %}" >New Comic</a> | 
            <a href="{% url 'sticky_new' %}" >New Sticky</a>
            <!-- <a href="{% url 'gallery_new' %}" > | New Art</a> -->
        {% endif %}
    </div>
{% block content %}{% endblock %}
    <!-- <div class="main-content-sticky">
        static bottom sticky test
    </div> -->
</body>
<footer>
    <ul>
        Social Links:
        <ul>
            <li><a href="https://twitter.com/MichelleGrenz" target=”_blank” class="social twitter" >Twitter</a></li>
            <li><a href="https://www.facebook.com/secondsightcomic" target=”_blank” class="social facebook">Facebook</a></li>
            <li><a href="https://emgee-art.tumblr.com" target=”_blank” class="social tumblr">Tumblr</a></li>
        </ul>
        Comic Mirrors:
        <ul>
            <li><a href="https://tapas.io/series/Second-Sight" target=”_blank” ><img src="../static/secondsight/tapas.png"></img></a></li>
            <li><a href="https://www.webtoons.com/en/challenge/second-sight/list?title_no=109825" target=”_blank”><img src="../static/secondsight/webtoons.png"></a></li>
        </ul>
    </ul>
</footer>
</html>

SecondSight/templates/secondsight/new.html
{% extends "secondsight/layout.html" %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="header"></div>
        <div class="main-content">
            <h1>{{ title }}</h1>
            <form method = "post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">SUBMIT</button>
            </form>
        </div>
    {% endif %}
{% endblock %}

SecondSight/templates/secondsight/news_detail.html
{% extends 'secondsight/layout.html' %}
{% load static %}

{% block content %}
<div class="header"></div>
<!--main content-->
<div class="main-content">
    {% if post.image %}
        <img src="/media/{{ post.image }}" id="banner"></img>
    {% endif %}
    <h1>
        {{  post.title }}
        {% if user.is_authenticated %}
            <a href="{% url 'news_edit' pk=post.id %}"> | Edit</a>
        {% endif %}
    </h1>
    <p>{{ post.created_date }}</p>
    <p>{{ post.text|safe }}</p>
    <ul>
    {% for comic in comics %}
        <li>
            <a href="{% url 'comic_detail' pk=comic.id %}">
                <img src="../../../media/{{ comic.image }}">
            </a>
        </li>
    {% endfor %}
    </ul>
    <!--/main content-->
</div>
{% endblock %}

SecondSight/templates/secondsight/news_manage.html
{% extends 'secondsight/layout.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="header"></div>
        <!--main content-->
        <div class="main-content">
            <h1>{{  post.title }}</h1>
            {% if post.manage == 'd' %}
                <p>
                    {% if user.is_authenticated %}
                        <h2>Are You Sure You Want to Delete This Post?</h2>
                        <a href="{% url 'news_delete' pk=post.id %}">Delete</a> / 
                        <a href="{% url 'news' %}">Cancel</a>
                    {% endif %}
                </p>
            {% else %}
                <h2>Your Post Has Been Updated</h2>
                <p><a href="{% url 'news' %}">continue</a></p>
            {% endif %}
        </div>
        <!--/main content-->
    {% endif %}
{% endblock %}

SecondSight/templates/secondsight/sticky_manage.html
{% extends 'secondsight/layout.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="header"></div>
        <!--main content-->
        <div class="main-content">
            <h1>{{  sticky.title }}</h1>
            {% if sticky.manage == 'd' %}
                <p>
                    {% if user.is_authenticated %}
                        <h2>Are You Sure You Want to Delete This Sticky?</h2>
                        <a href="{% url 'sticky_delete' pk=sticky.id %}">Delete</a> / 
                        <a href="{% url 'index' %}">Cancel</a>
                    {% endif %}
                </p>
            {% else %}
                <h2>Your Sticky Post Has Been Updated</h2>
                <p><a href="{% url 'news' %}">continue</a></p>
            {% endif %}
        </div>
        <!--/main content-->
    {% endif %}
{% endblock %}